In [1]:
import pandas as pd

df = pd.read_csv('../data/diabetic_data.csv')

df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [45]:
df.isnull().sum()

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
glimepiride-pioglitazone    0
metformin-rosiglitazone     0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

In [15]:
print((df == '?').sum())

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
glimepiride-pioglitazone    0
metformin-rosiglitazone     0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df = df.drop(columns = 'weight')

In [6]:
df.head()

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,?,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,?,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,?,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,?,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,?,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [7]:
df['race'] = df['race'].replace('?', 'N/A')

In [8]:
df['payer_code'] = df['payer_code'].replace('?', 'N/A')

In [9]:
df['medical_specialty'] = df['medical_specialty'].replace('?', 'N/A')

In [10]:
df['diag_1'] = df['diag_1'].replace('?', 'N/A')

In [11]:
df['diag_2'] = df['diag_2'].replace('?', 'N/A')

In [12]:
df['diag_3'] = df['diag_3'].replace('?', 'N/A')

In [43]:
df['max_glu_serum'] = df['max_glu_serum'].fillna('Not Tested')

In [44]:
df['A1Cresult'] = df['A1Cresult'].fillna('Not Tested')

In [20]:
df["encounter_id"].duplicated().sum()

np.int64(0)

In [21]:
df["patient_nbr"].duplicated().sum()

np.int64(30248)

In [22]:
df["patient_nbr"].nunique()

71518

In [23]:
len(df)

101766

In [28]:
df.dtypes

encounter_id                 int64
patient_nbr                  int64
race                        object
gender                      object
age                         object
admission_type_id            int64
discharge_disposition_id     int64
admission_source_id          int64
time_in_hospital             int64
payer_code                  object
medical_specialty           object
num_lab_procedures           int64
num_procedures               int64
num_medications              int64
number_outpatient            int64
number_emergency             int64
number_inpatient             int64
diag_1                      object
diag_2                      object
diag_3                      object
number_diagnoses             int64
max_glu_serum               object
A1Cresult                   object
metformin                   object
repaglinide                 object
nateglinide                 object
chlorpropamide              object
glimepiride                 object
acetohexamide               object
glipizide                   object
glyburide                   object
tolbutamide                 object
pioglitazone                object
rosiglitazone               object
acarbose                    object
miglitol                    object
troglitazone                object
tolazamide                  object
examide                     object
citoglipton                 object
insulin                     object
glyburide-metformin         object
glipizide-metformin         object
glimepiride-pioglitazone    object
metformin-rosiglitazone     object
metformin-pioglitazone      object
change                      object
diabetesMed                 object
readmitted                  object
dtype: object

In [26]:
df["time_in_hospital"] = df["time_in_hospital"].astype(int)

In [51]:
df['new_age'] = df['age'].str.replace(r'[\[\)]', '', regex = True)

In [52]:
df['new_age'].head()

0     0-10
1    10-20
2    20-30
3    30-40
4    40-50
Name: new_age, dtype: object

In [57]:
df['new_age'] = (
    df['age']
    .str.replace("[", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.split("-")
    .apply(lambda x: (int(x[0]) + int(x[1])) / 2)
)

In [59]:
df['new_age'].head()

0     5.0
1    15.0
2    25.0
3    35.0
4    45.0
Name: new_age, dtype: float64

In [61]:
df['new_age']= df['new_age'].astype(int)

In [76]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   admission_type_id         101766 non-null  int64
 6   discharge_disposition_id  101766 non-null  int64
 7   admission_source_id       101766 non-null  int64
 8   time_in_hospital          101766 non-null  int64
 9   payer_code                101766 non-null  object
 10  medical_specialty         101766 non-null  object
 11  num_lab_procedures        101766 non-null  int64
 12  num_procedures            101766 non-null  int64
 13  num_medications           101766 non-null  int64
 14  number_outpatient         101766 non-null  int64
 15  number_emergency          101766 non-null  int64
 16  number_inpatient          101766 non-null  int64
 17  diag_1                    101766 non-null  object
 18  diag_2                    101766 non-null  object
 19  diag_3                    101766 non-null  object
 20  number_diagnoses          101766 non-null  int64
 21  max_glu_serum             101766 non-null  object
 22  A1Cresult                 101766 non-null  object
 23  metformin                 101766 non-null  object
 24  repaglinide               101766 non-null  object
 25  nateglinide               101766 non-null  object
 26  chlorpropamide            101766 non-null  object
 27  glimepiride               101766 non-null  object
 28  acetohexamide             101766 non-null  object
 29  glipizide                 101766 non-null  object
 30  glyburide                 101766 non-null  object
 31  tolbutamide               101766 non-null  object
 32  pioglitazone              101766 non-null  object
 33  rosiglitazone             101766 non-null  object
 34  acarbose                  101766 non-null  object
 35  miglitol                  101766 non-null  object
 36  troglitazone              101766 non-null  object
 37  tolazamide                101766 non-null  object
 38  examide                   101766 non-null  object
 39  citoglipton               101766 non-null  object
 40  insulin                   101766 non-null  object
 41  glyburide-metformin       101766 non-null  object
 42  glipizide-metformin       101766 non-null  object
 43  glimepiride-pioglitazone  101766 non-null  object
 44  metformin-rosiglitazone   101766 non-null  object
 45  metformin-pioglitazone    101766 non-null  object
 46  change                    101766 non-null  object
 47  diabetesMed               101766 non-null  object
 48  readmitted                101766 non-null  object
 49  new_age                   101766 non-null  int64
dtypes: int64(14), object(36)
memory usage: 38.8+ MB

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,...,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,new_age
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,N/A,...,No,No,No,No,No,No,No,No,NO,5
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,N/A,...,Up,No,No,No,No,No,Ch,Yes,>30,15
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,N/A,...,No,No,No,No,No,No,No,Yes,NO,25
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,N/A,...,Up,No,No,No,No,No,Ch,Yes,NO,35
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,N/A,...,Steady,No,No,No,No,No,Ch,Yes,NO,45

In [72]:
df["time_in_hospital"].describe()

count    101766.000000
mean          4.395987
std           2.985108
min           1.000000
25%           2.000000
50%           4.000000
75%           6.000000
max          14.000000
Name: time_in_hospital, dtype: float64

In [65]:
(df["time_in_hospital"] < 0).sum()

np.int64(0)

In [66]:
(df["time_in_hospital"] == 0).sum()

np.int64(0)

In [67]:
(df["time_in_hospital"] > 14).sum()

np.int64(0)

In [68]:
(df["num_medications"] < 0).sum()

np.int64(0)

In [69]:
df["readmitted"].value_counts()

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [70]:
df["readmitted"].value_counts(normalize=True) * 100

readmitted
NO     53.911916
>30    34.928169
<30    11.159916
Name: proportion, dtype: float64

In [75]:
df.info()

df.describe()

df.isnull().sum()

df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   admission_type_id         101766 non-null  int64
 6   discharge_disposition_id  101766 non-null  int64
 7   admission_source_id       101766 non-null  int64
 8   time_in_hospital          101766 non-null  int64
 9   payer_code                101766 non-null  object
 10  medical_specialty         101766 non-null  object
 11  num_lab_procedures        101766 non-null  int64
 12  num_procedures            101766 non-null  int64
 13  num_medications           101766 non-null  int64
 14  number_outpatient         101766 non-null  int64
 15  number_emergency          101766 non-null  int64
 16  number_inpatient          101766 non-null  int64
 17  diag_1                    101766 non-null  object
 18  diag_2                    101766 non-null  object
 19  diag_3                    101766 non-null  object
 20  number_diagnoses          101766 non-null  int64
 21  max_glu_serum             101766 non-null  object
 22  A1Cresult                 101766 non-null  object
 23  metformin                 101766 non-null  object
 24  repaglinide               101766 non-null  object
 25  nateglinide               101766 non-null  object
 26  chlorpropamide            101766 non-null  object
 27  glimepiride               101766 non-null  object
 28  acetohexamide             101766 non-null  object
 29  glipizide                 101766 non-null  object
 30  glyburide                 101766 non-null  object
 31  tolbutamide               101766 non-null  object
 32  pioglitazone              101766 non-null  object
 33  rosiglitazone             101766 non-null  object
 34  acarbose                  101766 non-null  object
 35  miglitol                  101766 non-null  object
 36  troglitazone              101766 non-null  object
 37  tolazamide                101766 non-null  object
 38  examide                   101766 non-null  object
 39  citoglipton               101766 non-null  object
 40  insulin                   101766 non-null  object
 41  glyburide-metformin       101766 non-null  object
 42  glipizide-metformin       101766 non-null  object
 43  glimepiride-pioglitazone  101766 non-null  object
 44  metformin-rosiglitazone   101766 non-null  object
 45  metformin-pioglitazone    101766 non-null  object
 46  change                    101766 non-null  object
 47  diabetesMed               101766 non-null  object
 48  readmitted                101766 non-null  object
 49  new_age                   101766 non-null  int64
dtypes: int64(14), object(36)
memory usage: 38.8+ MB

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,...,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,new_age
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,N/A,...,No,No,No,No,No,No,No,No,NO,5
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,N/A,...,Up,No,No,No,No,No,Ch,Yes,>30,15
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,N/A,...,No,No,No,No,No,No,No,Yes,NO,25
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,N/A,...,Up,No,No,No,No,No,Ch,Yes,NO,35
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,N/A,...,Steady,No,No,No,No,No,Ch,Yes,NO,45

In [77]:
df.to_csv("cleaned_diabetic_data.csv", index=False)